### ISSUE TITLE
getContents ref gets ignored

### ISSUE THREAD

**Issue by Marcisbee** [octokit/octokit.js#1660] opened 2020-04-03 16:02 UTC
The problem I encountered is that `ref` gets ignored when using `octokit.repos.getContents`

Here's runkit example of the issue: https://runkit.com/marcisbee/5e87503619f7bc001370c3f6

There was a similar issue https://github.com/octokit/rest.js/issues/944 but I still can reproduce my issue here.

**Comment by gr2m** [comment] 2020-04-03 20:23
Thanks for providing a test reproducible test case, very helpful!

I found out that the problem is the trailing slash in the `path` parameter. `files/` results in a different response than `files`

See my test case for reference:
https://runkit.com/gr2m/octokit-rest-js-1660

It seems that the response when using `files/` is actually a 302 redirect. But the redirect URL is loosing the `?ref` query parameter. I think you found a legit bug with GitHub's REST API here :)

Could you please send a message to https://support.github.com/contact and ask them about it? If you could keep us posted in this issue about what you find out, I'd appreciate it. I can also reach out to support myself if you prefer

**Comment by Marcisbee** [comment] 2020-04-06 14:30
Thanks for reply!
I would prefer if you contacted as I don't fully know where the issue is there.

**Comment by gr2m** [comment] 2020-04-30 18:58
Here is the response I got from GitHub support:

> Apologies for the time it took us to get back to you. We recently saw some of our support request queues overflow and we are slowly regaining control of the situation.
> 
> This is expected behavior for the API, as queries should not contain trailing slashes. That said, GitHub obviously tries to adjust malformed API requests in a way that the trailing slash is stripped and I think preserving the parameters in this case would make a lot of sense.
> 
> Thanks for making us aware of this potential for improvement.

There is nothing actionable for me to do on this issue, so I'll close it if you don't mind. I'll post an update if I hear any follow up on the redirect

**Closed as completed by gr2m** 2020-04-30 18:58 UTC
Labels: Type: Bug, Status: Blocked
