### ISSUE TITLE
The type definition of ReposListLanguagesResponse only includes "C" and "Python"

### ISSUE THREAD

**Issue by busch-matthias** [octokit/octokit.js#1183] opened 2019-01-04 21:40 UTC
I use @octokit/rest@16.3.0
I stumbled over the function octokit.repos.listLanguages(...)
There i noticed that the type definition of the return value looks a bit suspicious:
``` type ReposListLanguagesResponse = { C: number; Python: number };```

At the moment i am sadly too stupid to suggest a better definition  : (

**Comment by gr2m** [comment] 2019-01-05 01:20
Hi Matthias, thanks for opening the issue!

The types are generated automatically based on the documentation, in this case https://developer.github.com/v3/repos/#list-languages

"The value shown for each language is the number of bytes of code written in that language." 

The `number` is derived from the example response 

```json
{
  "C": 78769,
  "Python": 7769
}
```

So that all sounds right to me?

**Comment by wolfy1339** [comment] 2019-01-05 04:56
What he's trying to convey in this issue is that there's missing the other languages in the types and they should be marked as possibly undefined.

**Comment by gr2m** [comment] 2019-01-05 05:08
Ah, thanks @wolfy1339, got it. 

The problem is that we can only derived the response schemas from the example responses in the documentation at this point. We are working on improving that but I cannot give an estimate.

I’m not sure if there is anything we can do right now to improve it as all this is generated automatically

**Comment by gr2m** [comment] 2019-01-16 01:35
I fear there is nothing we can do about it at this point, I’m afraid. I’ll close this issue but if there is any news in future I’ll comment to let you know about relevant updates

**Closed as completed by gr2m** 2019-01-16 01:35 UTC
Labels: Type: Bug

**Comment by wolfy1339** [comment] 2019-01-16 05:10
Maybe it could be possible to add this:
```typescript
{
    [key: string]: number
}
```
