### ISSUE TITLE
getTeams returns only the first page of the response

### ISSUE THREAD

**Issue by MikhailTymchukDX** [octokit/octokit.js#757] opened 2018-02-24 16:50 UTC
Getting teams for an organization returns only the first page of the result, thus truncating team count to 30:
```js
octokit.orgs.getTeams({
    'org': orgName
}
```

Examining with curl gives the same result (30 entries):
```
curl -u username https://api.github.com/orgs/orgName/teams
```
Querying with Ockotkit.NET returns all teams:
```csharp
octokit.Organization.Team.GetAll(orgName).Result;
```

**Comment by gr2m** [comment] 2018-02-24 17:26
Hi @MikhailTymchukDX, we are trying to keep the implementation of the JavaScript Octokit is close as possible, with all its design flaws. The GitHub REST API only returns 30 results by default, but you can ask for up to 100 per request, after that you have to paginate.

We have some methods to do that:
https://github.com/octokit/rest.js#pagination

We are looking into making that simpler as part of the [upcoming milestone](https://github.com/octokit/rest.js/milestone/3) so stay tuned.

As this is not a bug but expected behaviour, I'll close the issue, but feel free to ask follow up questions here

**Closed as completed by gr2m** 2018-02-24 17:26 UTC
