### ISSUE TITLE
Methods renamed in 16.37.0 causing breaking change

### ISSUE THREAD

**Issue by henrist** [octokit/octokit.js#1553] opened 2020-01-24 18:09 UTC
The changes in #1547 introduced a breaking change as these methods were renamed without a change in major version:

- `removeMember` => `removeMemberLegacy`
- `removeMembership` => `removeMembershipLegacy`

Code written for `<16.37.0` using these methods are now broken on reinstall if it has not locked the version. My library have had `^16.28.2` specified and broke the users of it. I see the methods were deprecated in 16.29.0

**Comment by gr2m** [comment] 2020-01-24 19:42
Hmm that should not have happened, the previous methods should still exist but be deprecated. I'm looking into it

**Comment by gr2m** [comment] 2020-01-24 19:46
I was able to reproduce it in https://runkit.com/gr2m/octokit-rest-js-1553. Very sorry for the trouble, I've been so careful, but missed something anyway :( Thanks for bringing that to my attention, I'll take care of it right away

**Comment by henrist** [comment] 2020-01-24 19:48
I think also there is something wrong happened to `teams.listMembers` and alike. It no longer has the `.endpoint` attribute available, as explained under https://octokit.github.io/rest.js/#pagination  (it is defined in TypeScript definition, but it's value is actually undefined).

**Comment by henrist** [comment] 2020-01-24 19:58
See https://runkit.com/henrist/octokit-rest-js-1553 for the addition for `teams.listMembers` endpoint

**Comment by gr2m** [comment] 2020-01-24 20:04
I think both is caused by the same problem.

`octokit1637.teams.listMembers` seems to be undefined already, I wonder why `octokit1637.teams.listMembers.endpoint` is not throwing

**Comment by henrist** [comment] 2020-01-24 20:12
> `octokit1637.teams.listMembers` seems to be undefined already, I wonder why `octokit1637.teams.listMembers.endpoint` is not throwing

`listMembers` is preserved and not renamed. But neither `listMembers.endpoint` nor `listMembersLegacy.endpoint` is defined.

**Comment by gr2m** [comment] 2020-01-24 20:43
A few different things happened here:

- The problem with `octokit.teams.removeMember()` was already fixed, but the automated update via https://github.com/octokit/routes/ didn't work as it should. Manual update fixed that one
- The problem with `octokit.teams.removeMembership()` was that I missed this particular URL in the method deprecations. That's something I've to manually keep track of for the SDKs. It's going to be fixed via https://github.com/octokit/routes/pull/623 and the update that comes through that.

Are there any other methods that you found missing?

I'm not yet sure about the missing `.endpoint()` method, still looking into this one. I'm quite sure it's related to deprecated methods, as all deprecated methods seem to be missing the `.endpoint()` method

**Comment by henrist** [comment] 2020-01-24 20:59
> Are there any other methods that you found missing?

Not that I've seen, but I can't rule it out.

**Comment by gr2m** [comment] 2020-01-24 21:19
could you check if all your tests pass with https://github.com/octokit/rest.js/pull/1554?

**Comment by henrist** [comment] 2020-01-24 21:36
Looking good :+1:

**Closed as completed** 2020-01-24 21:38 UTC
Labels: Type: Bug
