### ISSUE TITLE
[BUG]: Error when importing react component with octokit dependency

### ISSUE THREAD

**Issue by rwxmad** [octokit/octokit.js#2447] opened 2023-05-13 17:37 UTC
### What happened?

I have a react+typescript component that has an octokit dependency.
```
import React, { FC, useEffect, useState } from "react";
import { Octokit } from "octokit";

export const Graph: FC<IProps> = ({ token, theme }) => {...code}

```
Project structure:

```javascript
.
├── example
│  ├── public
│  │  └── index.html
│  ├── src
│  │  ├── App.tsx
│  │  ├── index.css
│  │  └── index.tsx
│  ├── .gitignore
│  ├── package-lock.json
│  ├── package.json
│  ├── README.md
│  └── tsconfig.json
├── lib
│  ├── components
│  │  ├── Graph.d.ts
│  │  └── Graph.js
│  ├── index.d.ts
│  └── index.js
├── src
│  ├── components
│  │  └── Graph.tsx
│  └── index.tsx
├── .gitignore
├── package-lock.json
├── package.json
└── tsconfig.json
```

I use tsc to build everything from src to the lib folder, and in the example folder I created a project using create-react-app, where I import the component from lib/index.js, which was compiled with tsc. But when I run the application in the folder example produces an error:
```javascript
Failed to parse source map from '/Users/rwxmad/code/github/react-github-contribution-graph/node_modules/@octokit/auth-app/dist-node/index.js.map' file: Error: ENOENT: no such file or directory, open '/Users/rwxmad/code/github/react-github-contribution-graph/node_modules/@octokit/auth-app/dist-node/index.js.map'
```
How to fix that error?

### Versions

Octokit v2.0.14
NodeJs v19.8.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment] 2023-05-13 17:42
Duplicate of https://github.com/octokit/auth-app.js/issues/474

**Closed as not planned** 2023-05-13 17:43 UTC
Labels: Type: Bug, Status: Triage

**Comment by rwxmad** [comment] 2023-05-17 14:31
@wolfy1339  still not working, how to fix?

**Comment by wolfy1339** [comment] 2023-05-17 20:52
Can you share the versions for **All** Octokit modules installed?

The ones listed in your lock file

**Comment by rwxmad** [comment] 2023-05-17 21:24
> Can you share the versions for **All** Octokit modules installed?
> 
> The ones listed in your lock file

https://github.com/rwxmad/react-github-contribution-graph/blob/main/package-lock.json

**Comment by rwxmad** [comment] 2023-05-17 21:34
> Can you share the versions for **All** Octokit modules installed?
> 
> The ones listed in your lock file

https://github.com/rwxmad/react-github-contribution-graph/blob/main/package-lock.json

Installed via npm i octokit

**Comment by wolfy1339** [comment] 2023-05-17 21:43
I believe in this case, it would be https://github.com/octokit/request.js/pull/584 that is now blocking you

**Comment by rwxmad** [comment] 2023-05-17 21:50
> I believe in this case, it would be octokit/request.js#584 that is now blocking you

Thank you for your help, I'll be waiting then
