### ISSUE TITLE
Octokit OAuth configuration does not work

### ISSUE THREAD

**Issue by plummer-flex** [octokit/octokit.js#1832] opened 2020-08-11 01:13 UTC
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [x] GitHub Enterprise Server: 2.19
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├─┬ @octokit/auth-app@2.4.14
│ ├─┬ @octokit/request@5.4.7
│ │ ├─┬ @octokit/endpoint@6.0.5
│ ├─┬ @octokit/request-error@2.0.2
│ ├─┬ @octokit/types@5.4.0
├─┬ @octokit/auth-oauth-app@3.0.5
├─┬ @octokit/plugin-enterprise-server@7.4.5
├─┬ @octokit/rest@17.11.2
│ ├─┬ @octokit/core@2.5.4
│ │ ├─┬ @octokit/auth-token@2.4.2
│ │ ├─┬ @octokit/graphql@4.5.3
│ ├─┬ @octokit/plugin-paginate-rest@2.3.0
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@3.17.0
│   ├─┬ @octokit/types@4.1.10
```

**What happened?**
Trying to set up application oauth in octokit enterprise instance.  The token isn't being retrieved and/or stored when the octokit insance is initialized. 

```js
const { enterpriseServer219Admin } = require('@octokit/plugin-enterprise-server');
const { createOAuthAppAuth } = require('@octokit/auth-oauth-app');
const { Octokit } = require('@octokit/rest');

const someFunction = async () => {
  const baseUrl = process.env.GHE_API;
  const clientId = process.env.CLIENT_ID;
  const clientSecret = process.env.CLIENT_SECRET;

  const OctokitEnterprise219 = Octokit.plugin(enterpriseServer219Admin);

     
  const octokit = new OctokitEnterprise219({
    authStrategy: createOAuthAppAuth,
    auth: { clientId, clientSecret },
    baseUrl,
  });

  const app = await octokit.apps.getAuthenticated();
}
```

`app` results in an error that the JWT could not be decoded.

However, if I am to run 

```js
const auth = await octokit.auth({type: 'oauth'});
```

I get an auth object with the authorization token.

```js
{
  type: 'oauth-app',
  clientId: 'XXXXXX",
  clientSecret: 'XXXXXX',
  headers: {
    authorization: 'basic XXXXXX'
  }
}
```

The documentation on oauth is unclear.  I presume to be missing a step.

**Minimal test case to reproduce the problem**

**What did you expect to happen?**

The octokit instance is authenticated.

**What the problem might be**
Configuration issue.

**Comment by gr2m** [comment] 2020-08-11 03:54
The endpoint for `octokit.apps.getAuthenticated()` is for GitHub Apps only, you need to authenticate using a JSON Web Token (JWT) in order to access it. Which means you need to use `@octokit/auth-app` instead and pass `id` and `privateKey`

What are you trying to achieve?

**Comment by plummer-flex** [comment] 2020-08-11 14:24
@gr2m Ah, so OAuth would be useless in my usecase.  I see.  

I was attempting to migrate to OAuth with ClientID/Secret from PEM key.  With PEM key, I am getting this error:

```
HttpError: 'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires
```


Code:

```
      const privateKey = process.env.GHE_KEY;
      const baseUrl = process.env.GHE_API;

      const OctokitEnterprise219 = Octokit.plugin(enterpriseServer219Admin);

      const octokit = new OctokitEnterprise219({
        authStrategy: createAppAuth,
        auth: {
          id: XX,
          installationId: XX,
          privateKey,
        },
        baseUrl,
      });
      const app = await octokit.apps.getAuthenticated();
      console.log(app);
```

Then end goal here is an integration test that checks to make sure the correct app is being referenced and the PEMkey works.

FWIW, I get the same error when trying to hit `github.com` or a custom Enterprise installation.

```
      const privateKey = fs.readFileSync('.ghekey', 'utf-8');

      const octokit = new Octokit({
        authStrategy: createAppAuth,
        auth: {
          id: XXXX,
          installationId: XXXX,
          privateKey,
        },
      });
      const app = await octokit.apps.getAuthenticated();
      console.log(app);
```

**Comment by gr2m** [comment] 2020-08-11 14:51
I was able to reproduce the problem:
https://runkit.com/gr2m/octokit-rest-js-1832/1.0.0

This is very odd, because I'm using the above setup a lot. It does not fail consistently, when I rerun the request it fails about every 3rd to 4th time on runkit.com. I'm investigating

**Comment by plummer-flex** [comment] 2020-08-11 14:55
@gr2m Yeah, it was working in March, but our feature was never released, so we didn't run integration tests again until yesterday.  Thanks for looking into it.

**Comment by gr2m** [comment] 2020-08-11 15:18
I cannot reproduce the problem locally. WHen it occured in the past, it was often times caused by an out-of-sync system clock. Could you make sure that this is not the cause of the problem in your case?

I'll contact the runkit.com folks to debug why it might fail in some cases. It might be a timezone issue, too ...

**Comment by gr2m** [comment] 2020-08-11 15:18
See https://github.com/probot/probot/issues/1257#issuecomment-656143529 for a comment to fix system time

**Comment by gr2m** [comment] 2020-08-11 15:25
It looks like the problem on runkit is system time, too. I've expanded the test case to log out system time and time from GitHub, and they are over a minute apart:

https://runkit.com/gr2m/octokit-rest-js-1832/3.0.0

**Comment by gr2m** [comment] 2020-08-11 15:35
I'm looking into improving the error message and/or making the implementation more resilient:
https://github.com/octokit/auth-app.js/issues/146

**Comment by plummer-flex** [comment] 2020-08-11 16:54
Running this inside mocha, `Date()` returns 0.  I'd have to mock the `Date` api for `auth-app` to sign the token with an appropriate value?

**Comment by gr2m** [comment] 2020-08-11 17:01
mocking time in tests is a good idea, but you should also mock the responses that you receive from GitHub, so it shouldn't be a problem? You can mock responses either with https://github.com/nock/nock/ or with https://github.com/wheresrhys/fetch-mock. I like to use the latter lately, because it works in both browser and node. You can see how I use it here for example: https://github.com/octokit/core.js/blob/master/test/request.test.ts

**Comment by shumink** [comment] 2020-09-07 07:39
I'm having the same problem here

**Comment by gr2m** [comment] 2020-09-10 19:24
Please watch this pull request, it will likely resolve the problem:
https://github.com/octokit/auth-app.js/pull/164

**Comment by gr2m** [comment] 2020-09-10 19:26
I'll close the issue because the original question was about OAuth which was a misunderstanding and has been resolved. Later in the discussion we discussed problems about JWT errors due to out-of-sync system time. This issue is tracked here: https://github.com/octokit/auth-app.js/pull/164

**Closed as completed by gr2m** 2020-09-10 19:26 UTC
Labels: Type: Support
