### ISSUE TITLE
issues.addLabels makes an invalid request (v16.0.0, v15.18.0)

### ISSUE THREAD

**Issue by dominykas** [octokit/octokit.js#1127] opened 2018-11-21 15:32 UTC
`issues.addLabels` calls the endpoint with `{ labels: arrayOfLabels }`, whereas the API available on GitHub Entperise expects just the `arrayOfLabels` as the body of the request.

`v15.17.0` was fine.

Actual result:
```
{ HttpError: Invalid request.

For 'links/2/schema', {"labels"=>["latest", "blocked"]} is not an array.
    at response.text.then.message (/Users/dominykas/devel/projects/wave2/pipeline/node_modules/@octokit/request/lib/request.js:55:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Using `'x-github-enterprise-version': '2.14.6'`.

**Comment by gr2m** [comment] 2018-11-21 16:08
Ugh I’m sorry, I didn’t meant to have that change in v15.x, I’ll get that fixed. But it will be in v16.

We are discussing how to align Octokit versions with compatibility GHE releases, it is in flux. Another thing we are going to do is to scrape routes from the Enterprise docs such as https://developer.github.com/enterprise/2.14/v3/ and publish these in separate packages. If things work out, you’ll be able to do something like this

```js
const Octokit = require('@octokit/core')
  .plugin(require('@octokit/ghe-2.14-rest'))

const octokit = new Octokit({baseUrl: 'https://github.acme-inc.com'})
octokit.issues.addLabels({owner, repo, number, labels: ['foo', 'bar']})
// will send ["latest", "blocked"] in request body, without the "labels" namespace
```

**Comment by dominykas** [comment] 2018-11-21 16:15
Any other way to make v16 work on GHE then? Haven't looked at the docs just yet, but we could possibly make a raw request (we do have our own wrapper around this...)?

**Comment by dominykas** [comment] 2018-11-21 16:22
Or possibly until an alternative package is available - would you be very much against having an extra param to support this "legacy" mode? Admittedly, I'm not aware of the full effect and differences between the two APIs - just looking out for myself to simplify version management :)

**Comment by gr2m** [comment] 2018-11-21 16:32
Yes you can send raw requests using [`octokit.request`](https://github.com/octokit/rest.js#custom-requests). E.g. in your case you would do

```js
octokit.request('/repos/:owner/:repo/issues/:number/labels', {
  owner,
  repo,
  number,
  data: ['label1', 'label2']
})
```

I think the proper solution would be to keep the v15 docs accessible and you would keep using v15. If there are bugs in v15 we can make new v15 patch releases.

**Comment by dominykas** [comment] 2018-11-21 16:43
It would probably be also good to have a way to check the API compatibility in an easy way - might even allow us to have a unit test to verify that against a GHE instance - would at least highlight the possible issues when renovate opens up an upgrade PR.

Are there many other incompatibilities in v16? Not too keen on using an older version - managing the upgrades is not something that's worth spending time on (esp. when it's for non-critical tooling #famouslastwords).

**Comment by gr2m** [comment] 2018-11-21 16:52
> It would probably be also good to have a way to check the API compatibility in an easy way

I plan to use https://github.com/octokit/fixtures to record fixtures against GHE versions, too. Just didn’t get to it. I’d love to have some kind of flag in octokit/routes that says which GHE versions are supported, but there is no such thing right now and I don’t know if even GitHub themselves would know.

> Not too keen on using an older version

Not too keen on maintaining an older version ;) As I said, I hope we get to the point where we clearly state compatibility with GHE versions in Octokit’s breaking changes, and then keep official maintenance versions for people that depend on support for the respective GHE versions.

A first good step would be to keep docs for older versions around :D I'm looking into that right now and am open for suggestions

**Comment by gr2m** [comment] 2018-12-13 18:01
[v15.18.1](https://github.com/octokit/rest.js/releases/tag/v15.18.1) was released which includes the fix for `octokit.issues.addLabels()`, can you give it a try?

**Comment by dominykas** [comment] 2018-12-13 20:39
I'm on parental leave until the end of the year - but will set a reminder to check when I'm back.

Thanks!

**Comment by gr2m** [comment] 2018-12-13 21:04
Thanks, happy parenting :) Please reopen the issue if you still run into a problem

**Closed as completed by gr2m** 2018-12-13 21:04 UTC
Labels: Type: Bug

**Comment by milesj** [comment] 2019-01-02 22:34
Has the fix made it into the 16.x releases yet?

**Comment by gr2m** [comment] 2019-01-03 01:30
@milesj it won’t make it into the 16.x release, but I will document it in the v16 release notes.

You can use https://github.com/octokit/plugin-enterprise-rest.js with the enterprise version you need to support, the methods should all work on api.github.com, too.

**Comment by milesj** [comment] 2019-01-03 02:30
Awesome, thanks.

**Comment by mysticflute** [comment] 2019-02-14 17:38
@dominykas I see the routes issue is fixed but with plugin-enterprise-rest 2.1.1 I am still seeing this issue. Wonder if this monkey patch is still needed or is it working for you?

**Comment by mysticflute** [comment] 2019-02-14 17:56
nevermind, I was using the plugin incorrectly

**Comment by C1PendletonJones** [comment] 2019-05-09 18:05
Any chance a fix for this might land in v16 at some point?

**Comment by gr2m** [comment] 2019-05-09 18:14
It’s not a bug, v16 works as it should, it sends the request as it’s documented:
https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

If you need compatibility for older GitHub Enterprise version, use https://github.com/octokit/plugin-enterprise-compatibility.js

**Comment by C1PendletonJones** [comment] 2019-05-09 18:19
okay thanks 👍
