### ISSUE TITLE
repos.issues.createLabel() ignores description parameter

### ISSUE THREAD

**Issue by gizmodesbois** [octokit/octokit.js#1141] opened 2018-11-27 13:16 UTC
Hello everyone,

I'm currently developing a bot with [Probot](https://github.com/probot/probot) which use octokit/rest and I'm having an issue with the [repos.issues.createLabel](https://octokit.github.io/rest.js/#api-Issues-createLabel).

When I add the `description` inside my object to create a label, the label is created but the `description` is not attached to it.

Here is what I provide:

```
{
	owner: '...',
	repo: '...',
    name: 'Test',
    color: '2ecc71',
    description: 'Test description'
}
```

Here is what I receive:

```
 data:
   { id: ...,
     node_id: '...',
     url: 'https://api.github.com/repos/.../labels/Test',
     name: 'Test',
     color: '2ecc71',
     default: false },
  status: 201,
  headers: {...}
```

Thank you in advance.

**Comment by abhijeetps** [comment] 2018-11-27 13:21
+1 on this.
Facing the same issue.
The bot creates a label named `weekly-digest` but doesn't add a description to it.
Please note that the description is following *the character limit of 100 characters* as supported by GitHub.

https://github.com/probot/weekly-digest/blob/d7c545b0ae616bd24be2fa92727225e36e430d31/src/bin/postCreateLabel.js#L3-L9

**Comment by gr2m** [comment] 2018-11-28 01:41
I was not able to reproduce the issue, see my test case at https://runkit.com/gr2m/octokit-rest-js-1141/2.0.0

Note that Probot is still using v15 of `@octokit/rest` while https://octokit.github.io/rest.js/ shows docs for v16 and there have been plenty of changes in method and parameter names in that release. But my test case above tests both v15 & v16.

So I assume it’s something else. Can you share your code?

**Comment by srchase** [comment] 2018-12-04 01:19
I'm encountering this issue on v16.1:

```          
let params = {
  owner: 'foo',
  repo: 'bar',
  name: 'myLabelName',
  color: 'FFFFFF',
  description: 'myLabelDescription'
}

octokit.issues.createLabel(params)
```

updateLabel seems to have the same issue as well.

**Comment by gr2m** [comment] 2018-12-04 01:40
Could you please share a reproducible test case such as https://runkit.com/gr2m/octokit-rest-js-1141/2.0.0?

**Comment by srchase** [comment] 2018-12-04 17:13
Setting the accept header alleviated this issue:

```
const octokit = require('@octokit/rest')({
  headers: {
    accept: 'application/vnd.github.symmetra-preview+json'
  }
});
```

**Comment by gr2m** [comment] 2018-12-04 18:04
Setting the header made no difference, the `description` is still sent in the body:
https://runkit.com/gr2m/octokit-rest-js-1141/3.0.0

**Comment by gr2m** [comment] 2018-12-07 18:32
I’ll close the issue because I cannot find a bug for it right now, but please comment if you find a way to reproduce the problem you mentioned

**Closed as completed by gr2m** 2018-12-07 18:32 UTC
Labels: Type: Support

**Comment by yvele** [comment] 2018-12-20 12:01
Using the accept header did the trick for me 😉

**Comment by rdohms** [comment] 2019-01-10 21:31
@gr2m for what its worth, i faced the same issue and the header did indeed fix it for me as well. I'm guessing the description is in the payload, hence the tests are ok, but github is the one ignoring it in the absence of the header.

**Comment by gr2m** [comment] 2019-01-11 02:13
Thanks Rafael, that makes sense. The main problem is that the current docs don’t include the same documentation as the REST API docs: https://developer.github.com/v3/issues/labels/#create-a-label. 

![image](https://user-images.githubusercontent.com/39992/51009026-346aa400-1503-11e9-820d-b51625ae294f.png)

We do get this information via https://github.com/octokit/routes but it’s not currently rendered in the docs. I’m working on new docs right now, I’ve a lot of pain points with the current docs :) It’s work-in-progress at https://github.com/gr2m/gatsby-api-docs-playground

**Comment by kymikoloco** [comment] 2019-04-23 15:13
The header trick didn't work for me, but sending the preview request with the call to `createLabel` worked for me:

```
context.github.issues.createLabel(context.repo({
    name: label,
    color: randomLabelColor(),
    description: `Created by the ${appName} GitHub App.`,
    mediaType: {
      previews: ['symmetra']
    }
}))
```
