### ISSUE TITLE
getNextPage not correctly promisified

### ISSUE THREAD

**Issue by werne2j** [octokit/octokit.js#425] opened 2016-09-27 19:54 UTC
When using getNextPage, the function is returning before the http request is finished

**Comment by kaizensoze** [comment] 2016-09-27 20:13
Do you have a basic code sample I can test with git bisect to see if it broke recently?

**Comment by kaizensoze** [comment] 2016-09-27 20:50
Yeah I think the issue is that the getPage function is separate from the prepareApi function, which is retrofitted for promises. The getPage function also needs to be retrofitted for promises.

On the other hand, there's an old getAllPages method I got rid of in b7147e430fc0e72e68f8cfa0d724c67705c65fca due to user confusion, that might be a better alternative to add back into your local copy. I'd be willing to add it back in if there's enough demand for it.

Pull request definitely welcome for adding Promise support to the getPage function

**Comment by kyptov** [comment] 2016-10-01 10:53
`new Promise((reject, resolve) => {})` 
resolve goes first, possibly bug

**Comment by kaizensoze** [comment] 2016-10-01 17:51
The only place I see Promise with reject/resolve params is https://github.com/mikedeboer/node-github/blob/master/lib/index.js#L257, which has resolve being first.

**Comment by codydaig** [comment] 2016-10-01 18:43
On line 2 of @werne2j's code block, `reject` is first.

**Comment by kaizensoze** [comment] 2016-10-01 19:44
Oh crap, sorry I was thinking about the codebase. Thanks for pointing that out.

**Comment by kaizensoze** [comment] 2016-10-06 19:56
@werne2j, let us know if @kyptov's suggestion did the trick.

**Comment by werne2j** [comment] 2016-10-06 20:32
Oh that very well could have been the problem! I ended up copying the getAllPages method that you previously had and using bluebird to promisify it. Not a great solution at all, but it was during a hack week and did what i needed it to at the time. Thanks for the help!

```
function getAllPages(method, options, callback) {
  let result = [];
  const cont = (err, list) => {
    if (err) {
      return callback(err);
    }
    result = result.concat(list);
    if (!github.hasNextPage(list)) {
      return callback(null, result);
    }
    github.getNextPage(list, cont);
  };
  method(options, cont);
}

const getAllPagesAsync = Promise.promisify(getAllPages);

function getAllRepos() {
  return getAllPagesAsync(github.repos.getForOrg, { org: myOrg });
}
```

**Comment by kaizensoze** [comment] 2016-10-07 04:04
Sure thing. Sorry you couldn't find a better solution. I'm going to close this for now.

**Closed as completed by kaizensoze** 2016-10-07 04:04 UTC
