### ISSUE TITLE
[BUG]: Loading Octokit into Browser via Skypack fails (v2.0.15 and above)

### ISSUE THREAD

**Issue by hilbix** [octokit/octokit.js#2471] opened 2023-06-14 00:42 UTC
### What happened?

Sorry, I found no better category than "BUG" for this.
This could be MAINT, but loading Octokit from Browser is failing, so I doubt it is just some MAINT.

This failure can be seen on my page <https://valentin.hilbig.de/minion/gh.html>

- https://cdn.skypack.dev/octokit@v2.0.15 fails
- https://cdn.skypack.dev/octokit@v2.0.14 works
  - see <https://valentin.hilbig.de/minion/gh2.html>

Using Octokit via Browser as given in the README with

    <script type="module">import { Octokit, App } from 'https://cdn.skypack.dev/octokit'; window.octokit={Octokit,App}</script>

fails with following error:

```
[Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Failed to load node_modules/lru-cache/dist/mjs/index.js
  Unexpected token (406:4) in lru-cache/dist/mjs/index.js
Install failed.
Install failed.
```

Accompanied with:

```
Uncaught Error: [Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
    <anonymous> https://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV?from=@octokit/auth-app:20
[build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV:20:7](https://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV?from=@octokit/auth-app)
    <anonymous> https://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV?from=@octokit/auth-app:20
```

But:

- Looking at <https://www.skypack.dev/view/octokit> looks good
- Looking at <https://www.skypack.dev/view/lru-cache> looks good for me as well

Note that I am just a naive user following your instructions with absolutely no clue what's going on behind the scenes with negative experience with NPM.  So I just realized, that Octokit suddenly fails for a reason that I am unable to *automatcially* repair myself.

-----------

I only found the workaround (how to use the older version) the hard way (trial and error).  This is a bad thing, as Skypack is there to provide us with the latest version, so we should abstain from hardcoding old versions.

And I do not know if this is the right thing to do in such a case.  Best would be there is some fallback, which triggers and loads some older version if the main version fails to load.  This should be automatic and require no code change.

If possible, please add a clue how to do this.  A like to some wiki or doc page should suffice.

**Using Octokit from Browsers should be a no-brainer**, hence I like to use the CDN (as stated in your README) to always access the latest version, and this should not fail.  Ever.

### Versions

Failing:

- https://cdn.skypack.dev/octokit
  - `octokit@v2.0.19-ypBGx51ixLri3sfCeesL/dist=es2019,mode=imports/optimized/octokit.js`

Working:

- https://cdn.skypack.dev/octokit@v2.0.14
  - `octokit@v2.0.14-WDHE0c1GgF96ore7BeW1/dist=es2019,mode=imports/optimized/octokit.js`

Environment:

- Ubuntu 22.04.2
  - firefox-esr    102.12.0esr+build1-0ubuntu0.22.04.1 amd64
  - snap firefox 114.0.1-1
  - snap chromium 114.0.5735.106

### Relevant log output

```shell
Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Failed to load node_modules/lru-cache/dist/mjs/index.js
  Unexpected token (406:4) in lru-cache/dist/mjs/index.js
Install failed.
Install failed. build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV:19:9
Uncaught Error: [Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
    <anonymous> https://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV?from=@octokit/auth-app:20
build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV:20:7
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment] 2023-06-14 00:43
Duplicate of #2450

**Closed as not planned by wolfy1339** 2023-06-14 00:43 UTC
Labels: Type: Bug, Status: Triage
