### ISSUE TITLE
Requests are mysteriously erroring

### ISSUE THREAD

**Issue by synicalsyntax** [octokit/octokit.js#992] opened 2018-08-25 00:45 UTC
I've been getting several requests that return a 500 Internal Server Error for no apparent reason, and I've been able to reproduce some errors through the [issues.getAll](https://octokit.github.io/rest.js/#api-Issues-getAll)/[list issues](https://developer.github.com/v3/issues/#list-issues) endpoint.

Here are my debug logs:
```
08-24-18 20:39:33: 2018-08-25T00:39:33.551Z octokit:rest REQUEST: { timeout: 0,
  agent: undefined,
  method: 'get',
  url: 'https://api.github.com/issues?filter=all&labels=in%20progress&per_page=100',
  headers: 
   { accept: 'application/vnd.github.squirrel-girl-preview',
     'user-agent': 'octokit/rest.js v15.10.0',
     authorization: '[REDACTED]' },
  body: undefined }
08-24-18 20:39:34: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
08-24-18 20:39:34: HttpError
    at response.text.then.message (/path/to/bot/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Is this a problem with octokit.js or the GitHub API? (I suspect it's the latter since it only errors when I specify a `labels` filter, but I'll close this issue once GitHub support replies)

**Comment by bkeepers** [comment] 2018-08-27 22:04
@synicalsyntax this looks to be an issue with the GitHub API. Let us know if you don't get a response from support.

**Comment by synicalsyntax** [comment] 2018-08-27 22:15
@bkeepers It's been 3 days since I sent the report, but I haven't gotten a response yet.

**Comment by Jenisonn** [comment] 2018-08-28 03:11
Somebody put this on my phone and laptop and I've spent months just trying
to figure it out and then a couple days ago all the information was there
under My Phone "Legal Dept". I already got most of that information on my
own by then. I did not consent to this. I've never heard of Android Open
Source until now. How do I remove it without deleting files and photos? How
do I find out who did this?   Thanks-Christy

**Comment by bkeepers** [comment] 2018-08-29 16:10
@synicalsyntax I just searched our support system and don't see a message from you.

Could you post an excerpt of the code you're using that is causing the error?

**Comment by synicalsyntax** [comment] 2018-08-29 20:08
@bkeepers Weird, I sent a second request for support a few hours before you just commented on this issue.

Anyways, here's my code that throws the error (you can see my debug logs in the initial issue post):
```js
client.issues.getAll({filter: "all", labels: "in progress"}).then(response => console.log(response.data.length));
```

However, this works fine:
```js
client.issues.getAll({filter: "all"}).then(response => console.log(response.data.length));
```

**Comment by BPScott** [comment] 2018-08-30 18:16
Hi @synicalsyntax, your debug log contains `You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:`. It would be helpful if you could add a `.catch()` to your promise so you can see the error message returned from the API server. It might help tracking down the root cause of the issue.

```
client.issues.getAll({filter: "all", labels: "in progress"})
  .then(response => console.log(response.data.length))
  .catch(response => console.log(response));
```

**Comment by synicalsyntax** [comment] 2018-08-30 19:41
Yes, I included the error output in the issue description:

```
08-24-18 20:39:34: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
08-24-18 20:39:34: HttpError
    at response.text.then.message (/path/to/bot/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

It's because the GitHub API is throwing a 500 error for some weird reason.

**Comment by synicalsyntax** [comment] 2018-09-01 04:08
@bkeepers I still haven't gotten a response from GitHub support, so I'm sending a request again. If you can, please look into the issue! Thanks.

![screenshot at aug 31 21-06-22](https://user-images.githubusercontent.com/15116870/44942210-bc74bc00-ad61-11e8-9213-c482129a34f0.png)

**Comment by bkeepers** [comment] 2018-09-04 14:26
@synicalsyntax I still don't see your support request, but I pinged our friends on the support team and am trying figure out why.

In the mean time…what is the App ID that you're making the request with?

**Comment by synicalsyntax** [comment] 2018-09-04 16:53
@bkeepers I'm actually authenticating with a user account through basic username/password, not an OAuth/GitHub app.

**Comment by bkeepers** [comment] 2018-09-05 12:31
@synicalsyntax ok, looks like support got back to you and the issue is a GitHub bug that is being investigated. I'm going to close this out since it doesn't look like an issue we can fix in this repo, but let me know if you don't hear back soon and I'll look into it.

**Closed as completed by bkeepers** 2018-09-05 12:31 UTC
