### ISSUE TITLE
Typecheck issue in the distributed npm package: `Cannot find module '@octokit/request-error'`

### ISSUE THREAD

**Issue by jakub-g** [octokit/octokit.js#2193] opened 2022-01-21 13:43 UTC
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

```
yarn init -2
yarn add octokit typescript
echo "import { Octokit } from 'octokit';" >> index.ts
touch tsconfig.json # edit as below
yarn tsc
```

`tsconfig.json` contents:
```
{
    "compilerOptions": {
        "allowJs": true,
        "lib": ["es2019", "dom", "dom.iterable", "es2019.array"],
    }
}
```

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

1.7.1

### What happened?

I was trying to upgrade from v1.0.3 and it didn't have this issue. With 1.7.1 typecheck complains:

```
.yarn/cache/octokit-npm-1.7.1-bfebbb1c97-95a1222f45.zip/node_modules/octokit/dist-types/app.d.ts:8:42 - error TS2307: Cannot find module '@octokit/request-error' or its corresponding type declarations.

8             retryRequest: (error: import("@octokit/request-error").RequestError, retries: number, retryAfter: number) => import("@octokit/request-error").RequestError;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~

.yarn/cache/octokit-npm-1.7.1-bfebbb1c97-95a1222f45.zip/node_modules/octokit/dist-types/app.d.ts:8:129 - error TS2307: Cannot find module '@octokit/request-error' or its corresponding type declarations.

8             retryRequest: (error: import("@octokit/request-error").RequestError, retries: number, retryAfter: number) => import("@octokit/request-error").RequestError;
                                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~

.yarn/cache/octokit-npm-1.7.1-bfebbb1c97-95a1222f45.zip/node_modules/octokit/dist-types/app.d.ts:11:22 - error TS2307: Cannot find module '@octokit/webhooks' or its corresponding type declarations.

11     webhooks: import("@octokit/webhooks").Webhooks<{
                        ~~~~~~~~~~~~~~~~~~~

.yarn/cache/octokit-npm-1.7.1-bfebbb1c97-95a1222f45.zip/node_modules/octokit/dist-types/app.d.ts:75:42 - error TS2307: Cannot find module '@octokit/request-error' or its corresponding type declarations.

75             retryRequest: (error: import("@octokit/request-error").RequestError, retries: number, retryAfter: number) => import("@octokit/request-error").RequestError;
                                            ~~~~~~~~~~~~~~~~~~~~~~~~

.yarn/cache/octokit-npm-1.7.1-bfebbb1c97-95a1222f45.zip/node_modules/octokit/dist-types/app.d.ts:75:129 - error TS2307: Cannot find module '@octokit/request-error' or its corresponding type declarations.

75             retryRequest: (error: import("@octokit/request-error").RequestError, retries: number, retryAfter: number) => import("@octokit/request-error").RequestError;
                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~

```

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by wolfy1339** [comment] 2022-01-21 14:39
I'm not sure if this will help, but you need to use the `strict` option in your `tsconfig.json` to get proper types.

I don't see any difference in `app.ts`, or other files that would make these errors appear now.

**Comment by wolfy1339** [comment] 2022-01-21 21:53
This seems to be an issue with how `yarn` resolves packages, as I cannot reproduce it when using `npm`

Unfortunately the JS octokit libraries no longer have an active maintainer.

You can read about it in [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174), subscribe to it for further updates.

**Comment by jakub-g** [comment] 2022-01-24 10:52
@wolfy1339 thanks for your replies and for all the info. I will have a deeper look on my side when I have some time.

We do use `strict` option in `tsconfig` by the way (I just shrank the file contents for the min repro).

**Comment by wolfy1339** [comment] 2022-07-04 20:51
As can be seen in the published types: https://unpkg.com/browse/octokit@1.8.1/dist-types/app.d.ts

The file imports the `@octokit/request-error`, `@octokit/webhooks`, and other octokit modules.

This seems to be an issue with how TypeScript is resolving the types and how they are defined.
I don't think there is anything that can be done here at this time.

**Comment by wolfy1339** [comment] 2023-08-01 23:52
Closing as there hasn't been any activity for over a year and there isn't anything actionable from our end

**Closed as not planned by wolfy1339** 2023-08-01 23:52 UTC
Labels: Type: Bug, typescript
