### ISSUE TITLE
TypeError: Octokit is not a function on version upgrade (16.36.0 ---> 17.9.0)

### ISSUE THREAD

**Issue by srihitha97** [octokit/octokit.js#1711] opened 2020-05-13 12:11 UTC
Hi,

On upgrading the package octokit/rest from 16.36.0 ---> 17.9.0, we are facing the below error on running npm t:

```
Git Api test
       "before each" hook for "resolves with repo names when octokit successfully resolves":
     TypeError: Octokit is not a function
      at Object.<anonymous> (lib/git-apis.js:9:192)
      at Module.replacementCompile (node_modules/append-transform/index.js:60:13)
      at Object.<anonymous> (node_modules/append-transform/index.js:64:4)
      at require (internal/module.js:11:18)
      at Context.<anonymous> (test/lib/git-apis-test.js:26:15)
```
This is the place we are using octokit:

```
const Octokit = require('@octokit/rest')

const octokit = Octokit({ auth: process.env.GIT_TOKEN, baseUrl: 'xyz' })

async function getAllReposForOrg (query) {
  const repos = await octokit
    .paginate(query)
  return repos.map(repo => repo.name)
}

module.exports = {
  getAllReposForOrg: getAllReposForOrg
}
```
Also,

```
return gitApis.getAllReposForOrg('xyz')
      .then((repoNames) => {
        
      })
```
Is there any syntax change that needs to be done due to the version upgrade for the above code?

**Comment by gr2m** [comment] 2020-05-13 22:39
`Octokit` is now a proper class constructor, you'll have to do these changes

```diff
- const Octokit = require('@octokit/rest')
+ const { Octokit } = require('@octokit/rest')
- const octokit = Octokit({ auth: process.env.GIT_TOKEN, baseUrl: 'xyz' })
+ const octokit = new Octokit({ auth: process.env.GIT_TOKEN, baseUrl: 'xyz' })
```

Does that work for you?

**Comment by srihitha97** [comment] 2020-05-14 02:47
Yes, it has solved the TypeError issue but now the below testcase is failing:
```
it('resolves with repo names when octokit successfully resolves', () => {
    return gitApis.getAllReposForOrg('GET /search/repositories?abc')
      .then((repoNames) => {
        return expect(repoNames).to.eql(['repo1', 'repo2'])
      })
```
with error:
```
AssertionError: expected '[null]' to deeply equal [ 'repo1', 'repo2' ]
```

Here, `repoNames` is turning out to be undefined, any idea why?

**Comment by gr2m** [comment] 2020-05-14 18:04
It looks like a code excempt from a test. Did you mock the http requests? That's what might cause the problem.

Some notes

- `?abc` does nothing. Did you mean `?q=abc`? In that case you can do this

  ```js
  await octokit.paginate('GET /search/repositories', { q: 'abc' })
  ```

- if you want to map the results to just the name property, you can pass a map function. It will greatly reduce memory usage, because instead of keeping all the full responses in memory before resolving, it will only need to keep arrays of names

  ```js
  await octokit.paginate('GET /search/repositories', { q: 'abc' }, response => response.data.map(repository => repository.name))
  ```

**Comment by srihitha97** [comment] 2020-05-15 04:47
Yes, all the above were taken care of.

This is a more accurate representation of the test-case that's failing:
```
describe('Git Api test', () => {
  var gitApis
  beforeEach(function () {
    delete require.cache[require.resolve('../../lib/git-apis.js')]
    gitApis = require('../../lib/git-apis.js')
    nock('https://api.xyz.com')
      .log(console.log)
      .get('/search/repositories?q=abc')
      .times(1)
      .reply(200, { body: [{ name: 'repo1' }, { name: 'repo2' }] })
  })

  afterEach(function () {
    nock.cleanAll()
  })

  it('resolves with repo names when octokit successfully resolves', () => {
    return gitApis.getAllReposForOrg('GET /search/repositories?q=abc')
      .then((repoNames) => {
        return expect(repoNames).to.eql(['repo1', 'repo2'])
      })
  })
})
```
However, `repoNames` is turning out to be `undefined` after the version upgrade.

I believe the getAllReposForOrg function that's using Octokit isn’t working as expected (I have pasted this code snippet in the initial issue comment).

**Comment by gr2m** [comment] 2020-05-15 06:03
Could you please try to create a minimal test case on runkit.com that reproduce the problem? Here is an example of a test case I did: https://runkit.com/gr2m/5aa034f1440b420012a6eebf

**Closed as completed** 2020-06-20 16:47 UTC
Labels: Type: Support, Status: Needs Info
