### ISSUE TITLE
Why use var yet?

### ISSUE THREAD

**Issue by suissa** [octokit/octokit.js#538] opened 2017-05-19 08:38 UTC
Why use var yet?

![](http://i2.kym-cdn.com/entries/icons/original/000/004/006/y-u-no-guy.jpg)

**Comment by williamkapke** [comment] 2017-05-19 15:57
It is a lot of work to switch to `const` or `let`. It is conceptually simple- but regression issues _can_ creep in. New issues === more volunteer time required to fix.

Also, in some versions of Node (as recent as 6.x IIRC), `let` had performance problems.

That said- PRs from the community ARE accepted here 🎉 
... but I would spread the changes out over time to avoid break-the-world scenarios.

**Comment by jeffwilcox** [comment] 2017-06-09 15:05
FYI looks like more issues are being opened on this, might be worth consolidating, de-duplicating (i.e. https://github.com/mikedeboer/node-github/issues/542)

**Comment by kaizensoze** [comment] 2017-08-31 20:51
The code coverage of this repo is really bad (tests don't work), so to prioritize and avoid bikeshedding I'm going to close this.

**Closed as completed by kaizensoze** 2017-08-31 20:51 UTC
